# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b24c8fe51c131e98dd5e898c22cbbec744ed6f5b38ec04b8515b2e933e1c2bde50f2821141b130bbd1760092cf0b5bceee12d288c2bb842e9fe8773c8f410fd

test:
  secret_key_base: f3ab674d3fd06a61c1f9ee8904f4baf9a20ce767f6c1ae4a76eb0b3b38e645764b1965494e49c80fbb77976b30e5c70351fe32f271af95ae661a1c504312de9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
